### ISSUE TITLE
link to data is using an old data url?

### ISSUE THREAD

**Issue by stmnk** [PubChimps/CORD-19#1]
can you please update the notebook with the link to the used data?

I get an error when running this input box:

`!wget -nc -O /content/CORD-19.zip https://ibm.box.com/shared/static/2hx1mza3k9rxy981boppmrewurv1pp8v.zip
!unzip /content/CORD-19.zip -d /content/data`

**Comment by PubChimps** [comment]
@stmnk Box (IBM's version at least) sets shared links to expire by default after 24 hours? This one should never expire please try it https://ibm.box.com/shared/static/m8ualk8ke9bqxtzqz19osmnd5ryqeflu.zip
